# cuanto a costado el computador?
costo_de_pc_en_euros_con_accesorios = 660
descuento_dado_en_porcentaje_por_total_de_compra = 10

descuento_dado_en_porcentaje_por_total_de_compra = ((costo_de_pc_en_euros_con_accesorios*descuento_dado_en_porcentaje_por_total_de_compra)/100)
#costo total incluido descuento
print(round(costo_de_pc_en_euros_con_accesorios-descuento_dado_en_porcentaje_por_total_de_compra))



